name: spw-env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - affine=2.4.0
  - ampl-asl=1.0.0
  - asttokens=3.0.0
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - beautifulsoup4=4.13.5
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cartopy=0.25.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cftime=1.6.4
  - charset-normalizer=3.4.3
  - click=8.2.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.13.5
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-tools=12.9.86
  - cuda-version=12.9
  - cudnn=9.12.0.46
  - cycler=0.12.1
  - dask-core=2025.7.0
  - dask-geopandas=0.5.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - filelock=3.19.1
  - fiona=1.10.1
  - folium=0.20.0
  - fonttools=4.59.1
  - freetype=2.13.3
  - freexl=2.0.0
  - fsspec=2025.7.0
  - gdal=3.10.3
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.13.1
  - geotiff=1.7.4
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - greenlet=3.2.4
  - h2=4.2.0
  - h5netcdf=1.6.4
  - h5py=3.14.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipopt=3.14.19
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.9.1.4
  - libcudnn=9.12.0.46
  - libcudnn-dev=9.12.0.46
  - libcudss=0.6.0.5
  - libcufft=11.4.1.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcurl=8.14.1
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgdal-core=3.10.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgpg-error=1.55
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmagma=2.9.0
  - libmpdec=4.0.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libnvjitlink=12.9.86
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libpysal=4.13.0
  - libre2-11=2025.07.22
  - librttopo=1.1.0
  - libscotch=7.0.8
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libspral=2025.05.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libtorch=2.7.1
  - libudev1=257.7
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - locket=1.0.0
  - lxml=6.0.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - metis=5.1.0
  - minizip=4.0.10
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mumps-include=5.8.1
  - mumps-seq=5.8.1
  - munkres=1.1.4
  - muparser=2.3.5
  - nccl=2.27.7.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.5
  - nlohmann_json=3.12.0
  - nomkl=1.0
  - numpy=2.3.2
  - obspy=1.4.2
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.5.2
  - optree=0.17.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.5
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - platformdirs=4.4.0
  - ply=3.11
  - powerlaw=1.4.6
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycparser=2.22
  - pygments=2.19.2
  - pyogrio=0.11.0
  - pyomo=6.9.3
  - pyparsing=3.2.3
  - pyproj=3.7.2
  - pyshp=3.0.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-gil=3.13.5
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytorch=2.7.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=27.0.2
  - qhull=2020.2
  - rasterio=1.4.3
  - rasterstats=0.20.0
  - rdma-core=58.0
  - re2=2025.07.22
  - readline=8.2
  - requests=2.32.5
  - s2n=1.5.23
  - scikit-learn=1.7.1
  - scipy=1.16.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - shapely=2.1.1
  - simplejson=3.20.1
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - soupsieve=2.7
  - sqlalchemy=1.4.54
  - sqlite=3.50.4
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - sympy=1.14.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tobler=0.12.1
  - toolz=1.0.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - triton=3.3.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - xarray=2025.8.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - bezpy==0.1.1
      - pysecs==0.3.0
prefix: /home/pve_ubuntu/miniconda3/envs/spw-env
